name: 🐞 Bug Report
description: Report a bug across any of our applications
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome!
        Thanks for taking the time to fill out this bug! If you need real-time help, message us on Discord.
  - type: dropdown
    id: application
    attributes:
      label: Issue Type?
      options:
        - Curriculum
        - My Account
        - Other
      description: What type of issue is this?
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Short summary of the bug
      placeholder: e.g., form crashes on submit
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Include logs, browser info, screenshots, etc.
    validations:
      required: false
